FROM node:16-alpine

WORKDIR /var/www/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm build

FROM node:16-alpine AS production

WORKDIR /var/www/production

COPY --from=builder /var/www/app/package*.json ./

RUN npm install --production

COPY --from=builder /var/www/app/dist ./dist
COPY --from=builder /var/www/app/express.js ./

EXPOSE 3000

CMD ["node", "./express.js"]
